# Generated by Django 5.1.5 on 2025-01-27 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsAbstract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155)),
                ('value', models.CharField(max_length=5000)),
                ('cats', models.ManyToManyField(to='api_news.newscategories')),
                ('comments', models.ManyToManyField(to='api_news.newscomments')),
                ('rates', models.ManyToManyField(related_name='news_rates', to='api_news.newsrates')),
            ],
        ),
        migrations.RemoveField(
            model_name='news',
            name='cats',
        ),
        migrations.RemoveField(
            model_name='news',
            name='id',
        ),
        migrations.RemoveField(
            model_name='news',
            name='rates',
        ),
        migrations.RemoveField(
            model_name='news',
            name='reviews',
        ),
        migrations.RemoveField(
            model_name='news',
            name='title',
        ),
        migrations.RemoveField(
            model_name='news',
            name='value',
        ),
        migrations.CreateModel(
            name='Scratch',
            fields=[
                ('newsabstract_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api_news.newsabstract')),
            ],
            bases=('api_news.newsabstract',),
        ),
        migrations.AddField(
            model_name='news',
            name='newsabstract_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api_news.newsabstract'),
            preserve_default=False,
        ),
    ]
