# Generated by Django 5.1.5 on 2025-01-18 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_users', '0002_remove_users_is_student_remove_users_is_teacher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='avatar',
            field=models.ImageField(default='./images/avatar.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.CharField(choices=[('AD', 'Admin'), ('MOD', 'Moderator'), ('TCH', 'Teacher'), ('ST', 'Student'), ('AP', 'Applicant')], max_length=30),
        ),
    ]
