# Generated by Django 5.1.5 on 2025-01-18 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_users', '0003_users_avatar_alter_users_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
