# Generated by Django 5.1.5 on 2025-01-18 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_users', '0004_alter_users_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.CharField(unique=True),
        ),
    ]
