# Generated by Django 5.1.5 on 2025-01-19 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_users', '0005_alter_users_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='avatar',
            field=models.ImageField(default='C:\\projects\\CURRENT\\BFU-LMS\\backend\\lms\\api_users/images/avatar.png', upload_to=''),
        ),
    ]
