# Generated by Django 5.1.5 on 2025-01-19 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_users', '0006_alter_users_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('moderator', 'Moderator'), ('teacher', 'Teacher'), ('student', 'Student'), ('applicant', 'Applicant')], max_length=30),
        ),
    ]
