# Generated by Django 5.1.5 on 2025-01-19 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_users', '0007_alter_users_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='avatar',
            field=models.ImageField(default='https://t3.ftcdn.net/jpg/06/19/26/46/360_F_619264680_x2PBdGLF54sFe7kTBtAvZnPyXgvaRw0Y.jpg', upload_to=''),
        ),
    ]
