# Generated by Django 5.1.5 on 2025-01-31 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_users', '0010_userspermissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
                ('surname', models.CharField(max_length=155)),
                ('otchestvo', models.CharField(max_length=155)),
                ('avatar', models.FileField(default='media/default_images/user_avatar.png', upload_to='media/users/avatars/')),
                ('gender', models.CharField(choices=[('М', 'Мужской'), ('Ж', 'Женский')], max_length=7)),
                ('date_of_birth', models.DateField()),
                ('citizenship', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='users',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='users',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='users',
            name='last_name',
        ),
        migrations.AddField(
            model_name='users',
            name='number',
            field=models.CharField(default='+89826257477', max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='info',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_users.usersinfo'),
        ),
    ]
