# Generated by Django 5.1.5 on 2025-01-31 21:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_users', '0011_usersinfo_remove_users_avatar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersinfo',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
