# Generated by Django 5.1.5 on 2025-01-31 22:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_users', '0012_usersinfo_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='info',
        ),
        migrations.AlterField(
            model_name='usersinfo',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
