# Generated by Django 5.1.5 on 2025-01-31 23:29

import api_users.BLL.models.change_file_name
import api_users.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_users', '0013_remove_users_info_alter_usersinfo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='id',
            field=models.CharField(default='hel', editable=False, max_length=26, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='users',
            name='number',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('teacher', 'Teacher'), ('student', 'Student'), ('applicant', 'Applicant')], max_length=30),
        ),
        migrations.AlterField(
            model_name='usersinfo',
            name='avatar',
            field=models.FileField(default='media/default_images/user_avatar.png', upload_to=api_users.BLL.models.change_file_name.change_file_name, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png'])]),
        ),
    ]
