# Generated by Django 5.1.5 on 2025-02-05 11:47

import api_users.BLL.models.change_file_name
import django.core.validators
import django.db.models.deletion
import django_ulid.models
import ulid.api.api
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_users', '0015_alter_users_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='avatar',
            field=models.FileField(default='media/default_images/user_avatar.png', upload_to=api_users.BLL.models.change_file_name.change_file_name, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png'])]),
        ),
        migrations.AddField(
            model_name='users',
            name='name',
            field=models.CharField(default='2000-01-01', max_length=155),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='otchestvo',
            field=models.CharField(default='sadasdasdasd', max_length=155),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='surname',
            field=models.CharField(default='asddasdqwe', max_length=155),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='users',
            name='id',
            field=django_ulid.models.ULIDField(default=ulid.api.api.Api.new, editable=False, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='UsersPassport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('М', 'Мужской'), ('Ж', 'Женский')], max_length=7)),
                ('date_of_birth', models.DateField()),
                ('citizenship', models.CharField(max_length=200)),
                ('issued_by', models.CharField(max_length=255)),
                ('date_issuance', models.DateField()),
                ('code_subdepartment', models.IntegerField()),
                ('serial', models.IntegerField()),
                ('number', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='UsersInfo',
        ),
    ]
