# Generated by Django 5.1.5 on 2025-03-03 07:57

import django_ulid.models
import ulid.api.api
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_users', '0035_alter_users_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='id',
            field=django_ulid.models.ULIDField(default=ulid.api.api.Api.new, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userspassport',
            name='number',
            field=models.CharField(max_length=55, unique=True),
        ),
    ]
