# Generated by Django 5.1.5 on 2025-01-16 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='is_student',
        ),
        migrations.RemoveField(
            model_name='users',
            name='is_teacher',
        ),
        migrations.AddField(
            model_name='users',
            name='role',
            field=models.CharField(choices=[('AD', 'Admin'), ('MOD', 'Moderator'), ('TCH', 'Teacher'), ('ST', 'Student')], default='Admin', max_length=30),
            preserve_default=False,
        ),
    ]
