# Generated by Django 5.1.5 on 2025-02-09 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Directions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
                ('slug', models.CharField(max_length=155)),
                ('description', models.CharField(max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='DirectionsSubjectsThrough',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_directions.directions')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_directions.subjects')),
            ],
        ),
        migrations.AddField(
            model_name='directions',
            name='subjects',
            field=models.ManyToManyField(through='api_directions.DirectionsSubjectsThrough', to='api_directions.subjects'),
        ),
    ]
