# Generated by Django 5.1.5 on 2025-02-10 17:00

import api_directions.BLL.models.change_file_name
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_directions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
                ('description', models.CharField(max_length=2000)),
            ],
        ),
        migrations.RenameModel(
            old_name='DirectionsSubjectsThrough',
            new_name='DirectionsSubjectsThroughBudget',
        ),
        migrations.RemoveField(
            model_name='directions',
            name='subjects',
        ),
        migrations.AddField(
            model_name='directions',
            name='budget_places',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='directions',
            name='learning_time',
            field=models.DecimalField(decimal_places=2, default=4.1, max_digits=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='directions',
            name='paid_places',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='directions',
            name='photo',
            field=models.FileField(default='media/default_images/news_default.png', upload_to=api_directions.BLL.models.change_file_name.change_file_name),
        ),
        migrations.AddField(
            model_name='directions',
            name='subjects_budget',
            field=models.ManyToManyField(related_name='subject_budget', through='api_directions.DirectionsSubjectsThroughBudget', to='api_directions.subjects'),
        ),
        migrations.CreateModel(
            name='DirectionsSubjectsThroughPaid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_directions.directions')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_directions.subjects')),
            ],
        ),
        migrations.AddField(
            model_name='directions',
            name='subjects_paid',
            field=models.ManyToManyField(related_name='subject_paid', through='api_directions.DirectionsSubjectsThroughPaid', to='api_directions.subjects'),
        ),
        migrations.AddField(
            model_name='directions',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_directions.school'),
        ),
    ]
