# Generated by Django 5.1.5 on 2025-02-12 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_directions', '0002_school_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directions',
            name='subjects_budget',
        ),
        migrations.RemoveField(
            model_name='directionssubjectsthroughpaid',
            name='direction',
        ),
        migrations.RemoveField(
            model_name='directionssubjectsthroughpaid',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='directions',
            name='subjects_paid',
        ),
        migrations.CreateModel(
            name='DirectionsSubjectsThroughBudgetPaid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
                ('type_points', models.CharField(choices=[('B', 'Budget'), ('P', 'Paid')], max_length=30)),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_directions.directions')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_directions.subjects')),
            ],
        ),
        migrations.AddField(
            model_name='directions',
            name='subjects_budget_paid',
            field=models.ManyToManyField(related_name='subject_budget', through='api_directions.DirectionsSubjectsThroughBudgetPaid', to='api_directions.subjects'),
        ),
        migrations.DeleteModel(
            name='DirectionsSubjectsThroughBudget',
        ),
        migrations.DeleteModel(
            name='DirectionsSubjectsThroughPaid',
        ),
    ]
