# Generated by Django 5.1.5 on 2025-02-18 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_directions', '0003_remove_directions_subjects_budget_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='directions',
            name='form_ed',
            field=models.CharField(choices=[('O', 'Очная'), ('Z', 'Заочная')], default='O', max_length=20),
            preserve_default=False,
        ),
    ]
