# Generated by Django 5.1.5 on 2025-03-03 07:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_directions', '0004_directions_form_ed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectionsStudentsThrough',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_directions.directions')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='directions',
            name='students',
            field=models.ManyToManyField(through='api_directions.DirectionsStudentsThrough', to=settings.AUTH_USER_MODEL),
        ),
    ]
