# Generated by Django 5.1.5 on 2025-03-05 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_directions', '0005_directionsstudentsthrough_directions_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='directions',
            name='price_foreign',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='directions',
            name='price_russian',
            field=models.IntegerField(null=True),
        ),
    ]
