# Generated by Django 5.1.5 on 2025-02-09 15:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentEducationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=55)),
                ('date_issuance', models.DateField()),
                ('issued_by', models.CharField(max_length=155)),
                ('category_exams', models.CharField(choices=[('ЕГЭ', 'Единый Государственный экзамен'), ('ВЭ', 'ВСтупительные экзамены')])),
                ('category_documents', models.CharField(choices=[('Копия', 'Копия'), ('Копия', 'Копия')])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentForeignDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fp_number', models.CharField(max_length=55)),
                ('fp_date_issuance', models.DateField()),
                ('fp_expire_date', models.DateField()),
                ('fp_issued_by', models.CharField(max_length=155)),
                ('vs_type', models.CharField(max_length=55)),
                ('vs_number', models.CharField(max_length=25)),
                ('vs_date_issuance', models.DateField()),
                ('vs_date_expire', models.DateField()),
                ('vs_purpose', models.CharField(max_length=55)),
                ('vs_country_issuance', models.CharField(max_length=155)),
                ('mc_number', models.CharField(max_length=55)),
                ('mc_date_entry', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentRussianDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snils', models.IntegerField()),
                ('inn', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
