# Generated by Django 5.1.5 on 2025-02-09 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentforeigndocuments',
            name='vs_country_issuance',
        ),
        migrations.RemoveField(
            model_name='studentforeigndocuments',
            name='vs_date_expire',
        ),
        migrations.RemoveField(
            model_name='studentforeigndocuments',
            name='vs_date_issuance',
        ),
        migrations.RemoveField(
            model_name='studentforeigndocuments',
            name='vs_number',
        ),
        migrations.RemoveField(
            model_name='studentforeigndocuments',
            name='vs_purpose',
        ),
        migrations.RemoveField(
            model_name='studentforeigndocuments',
            name='vs_type',
        ),
    ]
