# Generated by Django 5.1.5 on 2025-03-03 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_students', '0002_remove_studentforeigndocuments_vs_country_issuance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studenteducationdocument',
            name='category_documents',
        ),
        migrations.RemoveField(
            model_name='studenteducationdocument',
            name='category_exams',
        ),
    ]
