# Generated by Django 5.1.5 on 2025-03-03 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_students', '0003_remove_studenteducationdocument_category_documents_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenteducationdocument',
            name='number',
            field=models.CharField(max_length=55, unique=True),
        ),
        migrations.AlterField(
            model_name='studentforeigndocuments',
            name='fp_number',
            field=models.CharField(max_length=55, unique=True),
        ),
        migrations.AlterField(
            model_name='studentforeigndocuments',
            name='mc_number',
            field=models.CharField(max_length=55, unique=True),
        ),
        migrations.AlterField(
            model_name='studentrussiandocuments',
            name='inn',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='studentrussiandocuments',
            name='snils',
            field=models.IntegerField(unique=True),
        ),
    ]
