# Generated by Django 5.1.5 on 2025-03-03 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_students', '0004_alter_studenteducationdocument_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentrussiandocuments',
            name='inn',
            field=models.CharField(unique=True),
        ),
        migrations.AlterField(
            model_name='studentrussiandocuments',
            name='snils',
            field=models.CharField(unique=True),
        ),
    ]
