# Generated by Django 5.1.5 on 2025-03-05 19:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_students', '0005_alter_studentrussiandocuments_inn_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studenteducationdocument',
            name='user',
        ),
        migrations.RemoveField(
            model_name='studentforeigndocuments',
            name='user',
        ),
        migrations.RemoveField(
            model_name='studentrussiandocuments',
            name='user',
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api_students.studenteducationdocument')),
                ('foreign_document', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_students.studentforeigndocuments')),
                ('russian_document', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_students.studentrussiandocuments')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
