# Generated by Django 5.1.5 on 2025-03-05 21:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_students', '0006_remove_studenteducationdocument_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studenteducationdocument',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentforeigndocuments',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentrussiandocuments',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='education_document',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_document', to='api_students.studenteducationdocument'),
        ),
        migrations.AlterField(
            model_name='student',
            name='foreign_document',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='foreign_document', to='api_students.studentforeigndocuments'),
        ),
        migrations.AlterField(
            model_name='student',
            name='russian_document',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='russian_document', to='api_students.studentrussiandocuments'),
        ),
    ]
